/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pi.bestdeal.gui;

/**
 *
 * @author Internet
 */
public class ChoixStat1 extends javax.swing.JPanel {

    /**
     * Creates new form ChoixStat1
     */
    public ChoixStat1() {
        initComponents();
        buttonGrouptype.add(jRadiosexe);
        buttonGrouptype.add(jRadiooperation);
        buttonGroupcat.add(jRadioconsult);
        buttonGroupcat.add(jRadiores);
        jRadiosexe.setSelected(true);
        jRadioconsult.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouptype = new javax.swing.ButtonGroup();
        buttonGroupcat = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadiosexe = new javax.swing.JRadioButton();
        jRadiooperation = new javax.swing.JRadioButton();
        jRadioconsult = new javax.swing.JRadioButton();
        jRadiores = new javax.swing.JRadioButton();

        jLabel1.setText("Type Statistique");

        jLabel2.setText("Categorie");

        jRadiosexe.setText("Par Sexe");

        jRadiooperation.setText("Par Nombre d'Opération");

        jRadioconsult.setText("Consultation");

        jRadiores.setText("Reservation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioconsult)
                    .addComponent(jRadiooperation)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jRadiosexe)
                    .addComponent(jRadiores))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadiosexe)
                .addGap(18, 18, 18)
                .addComponent(jRadiooperation)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioconsult)
                .addGap(18, 18, 18)
                .addComponent(jRadiores)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupcat;
    private javax.swing.ButtonGroup buttonGrouptype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioconsult;
    public javax.swing.JRadioButton jRadiooperation;
    public javax.swing.JRadioButton jRadiores;
    public javax.swing.JRadioButton jRadiosexe;
    // End of variables declaration//GEN-END:variables
}
