/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pi.bestdeal.gui;

import java.awt.event.KeyEvent;

/**
 *
 * @author hp
 */
public class Modifier_Deal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Modifier_Deal
     */
    public Modifier_Deal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLb_Nom_Deal = new javax.swing.JLabel();
        jLb_Pres = new javax.swing.JLabel();
        jlb_Desc = new javax.swing.JLabel();
        txt_Nom_Deal = new javax.swing.JTextField();
        txt_pres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_Desc = new javax.swing.JTextArea();
        jLb_DateD = new javax.swing.JLabel();
        jLb_DateF = new javax.swing.JLabel();
        jLb_nbPers = new javax.swing.JLabel();
        jLb_nb_min_pers = new javax.swing.JLabel();
        jLb_nb_max_pers = new javax.swing.JLabel();
        jLb_Prix = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txt_nbpers = new javax.swing.JTextField();
        txt_nb_min_pers = new javax.swing.JTextField();
        txt_nb_max_pers = new javax.swing.JTextField();
        txt_Prix = new javax.swing.JTextField();
        jBt_Annuler = new javax.swing.JButton();
        jBt_Enregistrer = new javax.swing.JButton();

        jLb_Nom_Deal.setText("Titre");

        jLb_Pres.setText("Préstataire");

        jlb_Desc.setText("Description");

        txt_Nom_Deal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Nom_DealKeyTyped(evt);
            }
        });

        txt_pres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_presKeyTyped(evt);
            }
        });

        txtArea_Desc.setColumns(20);
        txtArea_Desc.setRows(5);
        jScrollPane1.setViewportView(txtArea_Desc);

        jLb_DateD.setText("Date Début");

        jLb_DateF.setText("Date Fin");

        jLb_nbPers.setText("Nombre de Personne");

        jLb_nb_min_pers.setText("Nombre min de Personne");

        jLb_nb_max_pers.setText("Nombre max de Personne");

        jLb_Prix.setText("Prix");

        jDateChooser1.setDateFormatString("yyyy MMM d  ");

        jDateChooser2.setDateFormatString("yyyy MMM d  ");

        txt_nbpers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nbpersKeyTyped(evt);
            }
        });

        txt_nb_min_pers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nb_min_persKeyTyped(evt);
            }
        });

        txt_nb_max_pers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nb_max_persKeyTyped(evt);
            }
        });

        txt_Prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrixKeyTyped(evt);
            }
        });

        jBt_Annuler.setText("Annuler");
        jBt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_AnnulerActionPerformed(evt);
            }
        });

        jBt_Enregistrer.setText("Enregistrer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_Nom_Deal)
                    .addComponent(jlb_Desc)
                    .addComponent(jLb_Pres)
                    .addComponent(jLb_DateD)
                    .addComponent(jLb_DateF)
                    .addComponent(jLb_nbPers)
                    .addComponent(jLb_nb_min_pers)
                    .addComponent(jLb_nb_max_pers)
                    .addComponent(jLb_Prix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Prix)
                    .addComponent(txt_nb_max_pers)
                    .addComponent(txt_nb_min_pers)
                    .addComponent(txt_nbpers)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_pres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Nom_Deal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBt_Enregistrer)
                .addGap(62, 62, 62)
                .addComponent(jBt_Annuler)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Nom_Deal)
                    .addComponent(txt_Nom_Deal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Pres)
                    .addComponent(txt_pres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_Desc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_DateD)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_DateF)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_nbPers)
                    .addComponent(txt_nbpers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_nb_min_pers)
                    .addComponent(txt_nb_min_pers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_nb_max_pers)
                    .addComponent(txt_nb_max_pers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Prix)
                    .addComponent(txt_Prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBt_Annuler)
                    .addComponent(jBt_Enregistrer))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_AnnulerActionPerformed
        String Command= evt.getActionCommand();
        if (Command.equals("Annuler"))
        {
         Modifier_Deal JIF = new Modifier_Deal();
         JIF.show();
         this.setVisible(false);   
        }
    }//GEN-LAST:event_jBt_AnnulerActionPerformed

    private void txt_nbpersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nbpersKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)|| c== KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nbpersKeyTyped

    private void txt_nb_min_persKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nb_min_persKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)|| c== KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nb_min_persKeyTyped

    private void txt_nb_max_persKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nb_max_persKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)|| c== KeyEvent.VK_DELETE) )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nb_max_persKeyTyped

    private void txt_PrixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrixKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.')
        {
            getToolkit().beep();
            evt.consume();
        }
        if (evt.getKeyChar()=='.' && txt_Prix.getText().contains("."))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_PrixKeyTyped

    private void txt_Nom_DealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Nom_DealKeyTyped
        char c =evt.getKeyChar();
        if((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)|| c== KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_Nom_DealKeyTyped

    private void txt_presKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_presKeyTyped
         char c =evt.getKeyChar();
        if((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)|| c== KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_presKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_Annuler;
    private javax.swing.JButton jBt_Enregistrer;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLb_DateD;
    private javax.swing.JLabel jLb_DateF;
    private javax.swing.JLabel jLb_Nom_Deal;
    private javax.swing.JLabel jLb_Pres;
    private javax.swing.JLabel jLb_Prix;
    private javax.swing.JLabel jLb_nbPers;
    private javax.swing.JLabel jLb_nb_max_pers;
    private javax.swing.JLabel jLb_nb_min_pers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb_Desc;
    private javax.swing.JTextArea txtArea_Desc;
    private javax.swing.JTextField txt_Nom_Deal;
    private javax.swing.JTextField txt_Prix;
    private javax.swing.JTextField txt_nb_max_pers;
    private javax.swing.JTextField txt_nb_min_pers;
    private javax.swing.JTextField txt_nbpers;
    private javax.swing.JTextField txt_pres;
    // End of variables declaration//GEN-END:variables
}
